# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Cache": "00_config.ipynb",
         "Files": "00_config.ipynb",
         "Config": "00_config.ipynb",
         "MJD": "00_config.ipynb",
         "UTC": "00_config.ipynb",
         "day": "00_config.ipynb",
         "first_data": "00_config.ipynb",
         "PointSource": "00_config.ipynb",
         "EffectiveArea": "01_effective_area.ipynb",
         "InterpTable": "01_effective_area.ipynb",
         "effective_area_plots": "01_effective_area.ipynb",
         "get_gti": "02_gti.ipynb",
         "get_default_bins": "03_exposure.ipynb",
         "get_exposure": "03_exposure.ipynb",
         "get_contiguous_exposure": "03_exposure.ipynb",
         "get_binned_exposure": "03_exposure.ipynb",
         "get_photon_data": "04_photon_data.ipynb",
         "check_weights": "05_weights.ipynb",
         "add_weights": "05_weights.ipynb",
         "get_weight_hist": "05_weights.ipynb",
         "Poisson": "06_poisson.ipynb",
         "PoissonFitter": "06_poisson.ipynb",
         "get_cells": "07_cells.ipynb",
         "concatenate_cells": "07_cells.ipynb",
         "partition_cells": "07_cells.ipynb",
         "poisson_tolerance": "08_loglike.ipynb",
         "LogLike": "08_loglike.ipynb",
         "GaussianRep": "08_loglike.ipynb",
         "Gaussian2dRep": "08_loglike.ipynb",
         "PoissonRep": "08_loglike.ipynb",
         "PoissonRepTable": "08_loglike.ipynb",
         "fit_cells": "09_lightcurve.ipynb",
         "get_lightcurve": "09_lightcurve.ipynb",
         "flux_plot": "09_lightcurve.ipynb",
         "generate_cell": "10_simulation.ipynb",
         "simulate_cells": "10_simulation.ipynb"}

modules = ["config.py",
           "effective_area.py",
           "load_gti.py",
           "exposure.py",
           "photon_data.py",
           "weights.py",
           "poisson.py",
           "cells.py",
           "loglike.py",
           "lightcurve.py",
           "simulation.py"]

doc_url = "https://tburnett.github.io/wtlike/"

git_url = "https://github.com/tburnett/wtlike/tree/master/"

def custom_doc_links(name): return None
